# Built from this template : https://github.com/actions/setup-python
name: Python-Full-CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Install dependencies
        run: make sync
      - name: Run tests
        run: make test
      - name: Build docs
        run: make docs

      - name: Delete previous docs artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            ${{ github.head_ref || github.ref_name }}-docs
            ${{ github.head_ref || github.ref_name }}-test-report
          failOnError: false
      - name: Upload artifacts for docs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref || github.ref_name }}-docs
          path: ./documentation/build
      - name: Upload artifacts for test report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref || github.ref_name }}-test-report
          path: ./artifacts/test_report/